### ISSUE TITLE
Error detected while processing function ConflictedTabLabel

### ISSUE THREAD

**Issue by albasili** [christoomey/vim-conflicted#14]
This is what I get when calling ``:Conflicted`` in a repo that has a conflict.

**Comment by christoomey** [comment]
Hi @albasili, can you provide any additional info? Specifcally:

- What is the state of the repo when you run `:Conflicted`. How many conflicted files, all "Both modified", or are there any that are "Modify / Delete".
- Is there anything else shown if you run `:messages` in Vim?

**Comment by albasili** [comment]
Actually I think the error comes from somewhere else. By calling ``:Conflicted`` while being sure no conflicts exists I have this:
``` shell
Error detected while processing function <SNR>91_Conflicted[4]..<SNR>91_Merger[1]..<SNR>90_Diff:                                                                                                                                                                                
line   63:                                                                                                                                                                                                                                                                      
Traceback (most recent call last):                                                                                                                                                                                                                                              
  File "<string>", line 1, in <module>                                                                                                                                                                                                                                          
  File "/usr/lib/python3/dist-packages/powerline/vim.py", line 299, in statusline                                                                                                                                                                                               
    window, window_id, winnr = self.win_idx(window_id) or (None, None, None)                                                                                                                                                                                                    
  File "/usr/lib/python3/dist-packages/powerline/vim.py", line 276, in new_win_idx                                                                                                                                                                                              
    window.options['statusline'] = statusline                                                                                                                                                                                                                                   
vim.error: Vim:Traceback (most recent call last):                                                                                                                                                                                                                               
E858: Eval did not return a valid python object       
```

Is it something therefore related to powerline any python interaction?
